//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooksAPI.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> InvoiceStatus { get; set; }
    
        public virtual tblCart tblCart { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
