//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBooksAPI.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWishlist
    {
        public int id { get; set; }
        public string ISBN { get; set; }
        public int UserId { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
